const mapelData = [
    {
      order: 1,
      kategori: 'Mathematics',
      mapel: 'Algebra Basics',
      owner: 'Teacher A',
      kodekategori: 'MATH-ALG',
      jenisWaktu: 'Weekly',
      tanggalMulai: '2024-01-01',
      tanggalBerakhir: '2024-03-31',
      prasyarat: 'Basic Arithmetic',
      durasi: '12 weeks',
    },
    {
      order: 2,
      kategori: 'Science',
      mapel: 'Physics Fundamentals',
      owner: 'Teacher B',
      kodekategori: 'SCI-PHY',
      jenisWaktu: 'Daily',
      tanggalMulai: '2024-02-01',
      tanggalBerakhir: '2024-04-15',
      prasyarat: 'None',
      durasi: '10 weeks',
    },
    {
      order: 3,
      kategori: 'Language Arts',
      mapel: 'English Literature',
      owner: 'Teacher C',
      kodekategori: 'LANG-ENG',
      jenisWaktu: 'Bi-Weekly',
      tanggalMulai: '2024-01-15',
      tanggalBerakhir: '2024-05-30',
      prasyarat: 'Intermediate English',
      durasi: '15 weeks',
    },
    {
      order: 4,
      kategori: 'History',
      mapel: 'World History',
      owner: 'Teacher D',
      kodekategori: 'HIST-WRLD',
      jenisWaktu: 'Weekly',
      tanggalMulai: '2024-01-10',
      tanggalBerakhir: '2024-04-20',
      prasyarat: 'General Knowledge',
      durasi: '14 weeks',
    },
    {
      order: 5,
      kategori: 'Computer Science',
      mapel: 'Introduction to Programming',
      owner: 'Teacher E',
      kodekategori: 'COMP-PROG',
      jenisWaktu: 'Weekly',
      tanggalMulai: '2024-03-01',
      tanggalBerakhir: '2024-06-15',
      prasyarat: 'Basic Computer Knowledge',
      durasi: '16 weeks',
    },
  ];
  
  module.exports = mapelData;
  